# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class ApiService:
        service: str
        type: str
        url: str
    class App:
        name: str
        stage: str
    class AuthSecret:
        type: str
        value: str
    class BatchBucket:
        name: str
        type: str
    class CronSecret:
        type: str
        value: str
    class Frontend:
        type: str
        url: str
    class GoogleClientId:
        type: str
        value: str
    class GoogleClientSecret:
        type: str
        value: str
    class GrafanaAdminPassword:
        type: str
        value: str
    class LlmGateway:
        service: str
        type: str
        url: str
    class OpenRouterApiKey:
        type: str
        value: str
    class Postgres:
        database: str
        host: str
        password: str
        port: float
        type: str
        username: str
    class SesFromEmail:
        type: str
        value: str
    class StripePublishableKey:
        type: str
        value: str
    class StripeSecretKey:
        type: str
        value: str
    class StripeWebhookSecret:
        type: str
        value: str
    class VastApiKey:
        type: str
        value: str
    class Vpc:
        bastion: str
        type: str

